// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUgwIvEgaYG-K7A1ERTkmyWnqS7RVdCLU',
    appId: '1:706916583502:web:b3167da1b7c53ae1681b1f',
    messagingSenderId: '706916583502',
    projectId: 'meinho-26cd3',
    authDomain: 'meinho-26cd3.firebaseapp.com',
    databaseURL: 'https://meinho-26cd3-default-rtdb.firebaseio.com',
    storageBucket: 'meinho-26cd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAuJT0g0MpB4T2-Polb_I4w4ICOjSzweA',
    appId: '1:706916583502:android:dc9ca4690f750e23681b1f',
    messagingSenderId: '706916583502',
    projectId: 'meinho-26cd3',
    databaseURL: 'https://meinho-26cd3-default-rtdb.firebaseio.com',
    storageBucket: 'meinho-26cd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNNcFZekat1ibp3k-18MqegF27Nck6ZJY',
    appId: '1:706916583502:ios:810efaf001f32f95681b1f',
    messagingSenderId: '706916583502',
    projectId: 'meinho-26cd3',
    databaseURL: 'https://meinho-26cd3-default-rtdb.firebaseio.com',
    storageBucket: 'meinho-26cd3.firebasestorage.app',
    iosBundleId: 'com.example.meinho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNNcFZekat1ibp3k-18MqegF27Nck6ZJY',
    appId: '1:706916583502:ios:810efaf001f32f95681b1f',
    messagingSenderId: '706916583502',
    projectId: 'meinho-26cd3',
    databaseURL: 'https://meinho-26cd3-default-rtdb.firebaseio.com',
    storageBucket: 'meinho-26cd3.firebasestorage.app',
    iosBundleId: 'com.example.meinho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUgwIvEgaYG-K7A1ERTkmyWnqS7RVdCLU',
    appId: '1:706916583502:web:e24b13679c167908681b1f',
    messagingSenderId: '706916583502',
    projectId: 'meinho-26cd3',
    authDomain: 'meinho-26cd3.firebaseapp.com',
    databaseURL: 'https://meinho-26cd3-default-rtdb.firebaseio.com',
    storageBucket: 'meinho-26cd3.firebasestorage.app',
  );
}
